### ISSUE TITLE
Mobile Design Research

### ISSUE THREAD

**Issue by jkosem** [ipfs/mobile-design-guidelines#26]
**Week 12**

- [x] [Recruitment of experts for interviews](https://github.com/ipfs/mobile-design-guidelines/issues/24)
- [x] [Kick-off workshop with Protocol Labs](https://github.com/ipfs/mobile-design-guidelines/issues/8)

**Week 13**

- [x] [Expert interviews](https://github.com/ipfs/mobile-design-guidelines/issues/12)
- [x] [Recruitment of non-experts for interviews](https://github.com/ipfs/mobile-design-guidelines/issues/10)
- [x] [Non-experts interviews](https://github.com/ipfs/mobile-design-guidelines/issues/16)

**Week 14**

- [x] [Review of wider and additional contexts that affect mobile](https://github.com/ipfs/mobile-design-guidelines/issues/4)
- [x] [Survey review of mobile p2p applications](https://github.com/ipfs/mobile-design-guidelines/issues/25)
- [x] [Review, survey and audit of existing mobile sharing interaction patterns](https://github.com/ipfs/mobile-design-guidelines/issues/15)
- [x] [Writing and publication of blog post introducing the project research1](https://github.com/ipfs/mobile-design-guidelines/issues/14)

**Week 15**
- [x] [Consolidating of research into a readable resource in public repository](https://github.com/ipfs/mobile-design-guidelines/issues/17)
- [x] [Analysis of research and surveys](https://github.com/ipfs/mobile-design-guidelines/issues/18)
- [x] [Design strategy compiled and documented in repository](https://github.com/ipfs/mobile-design-guidelines/issues/19)
- [x] [Writing and publication of blog post summarising the project research](https://github.com/ipfs/mobile-design-guidelines/issues/20) (submitted for approval and blocked on publishing)

**After**
- [x] [Presentation of the project to IPFS stakeholders and community](https://github.com/ipfs/mobile-design-guidelines/issues/21)
