### ISSUE TITLE
Mobile Design Guidelines

### ISSUE THREAD

**Issue by jkosem** [ipfs/mobile-design-guidelines#45]
All of the issues in one issue to track the progress easily in one place

----

**Week 19**

- [x] [Design workshop to help translate research and direct design](https://github.com/ipfs/mobile-design-guidelines/issues/35)

**Week 20**

**Week 21**

**Week 22**

- [x] [Interaction design and production of user flows and use cases](https://github.com/ipfs/mobile-design-guidelines/issues/37)
- [x] [User interface, component and elements design](https://github.com/ipfs/mobile-design-guidelines/issues/36)

**Week 23**

- [x] [Documentation survey and collection of research and design materials](https://github.com/ipfs/mobile-design-guidelines/issues/39)

**Week 24**

- [x] [Compilation of assets and writing of documentation with development recommendations](https://github.com/ipfs/mobile-design-guidelines/issues/41)
- [x] [Writing of blog post summarising the project design](https://github.com/ipfs/mobile-design-guidelines/issues/42)

**Week 25**

- [x] [Publication of blog post summarising the project design](https://github.com/ipfs/mobile-design-guidelines/issues/42)
- [x] [Presentation of the project at IPFS Weekly or similar](https://github.com/ipfs/mobile-design-guidelines/issues/43)
